/**
 * Contract validation tests — uses real fixture files generated by
 * scripts/generate-fixtures.ts to validate the console against the
 * exact DAGent data contracts.
 *
 * Run: npx jest src/services/__tests__/contractValidation.test.ts
 */

import path from "path";
import { existsSync } from "fs";
import {
    getPipelineTelemetry,
    getSpecMarkdown,
    getFlightDataMtime,
    listPipelines,
} from "@/services/flightDataReader";
import type {
    FlightDataEnvelope,
} from "@/types/pipeline";
import { promises as fs } from "fs";

// ---------------------------------------------------------------------------
// Point the service at fixtures
// ---------------------------------------------------------------------------

const FIXTURES_DIR = path.join(__dirname, "..", "..", "..", "fixtures", "sample-app");

let originalTargetAppPath: string | undefined;

beforeAll(() => {
    if (!existsSync(FIXTURES_DIR)) {
        throw new Error(
            `Fixtures not found at ${FIXTURES_DIR}.\n` +
            `Run: npx tsx scripts/generate-fixtures.ts`
        );
    }
    originalTargetAppPath = process.env.TARGET_APP_PATH;
    process.env.TARGET_APP_PATH = FIXTURES_DIR;
});

afterAll(() => {
    if (originalTargetAppPath === undefined) {
        delete process.env.TARGET_APP_PATH;
    } else {
        process.env.TARGET_APP_PATH = originalTargetAppPath;
    }
});

// =========================================================================
// A. Discovery & Initialization
// =========================================================================

describe("A. Discovery & Initialization", () => {
    it("discovers active pipeline 'test-feature' from in-progress/", async () => {
        const pipelines = await listPipelines();
        const active = pipelines.find((p) => p.slug === "test-feature");
        expect(active).toBeDefined();
        expect(active!.overallStatus).toBe("active");
    });

    it("discovers archived pipeline 'old-feature' from archive/features/", async () => {
        const pipelines = await listPipelines();
        const archived = pipelines.find((p) => p.slug === "old-feature");
        expect(archived).toBeDefined();
        expect(archived!.overallStatus).toBe("completed");
    });

    it("lists both active and archived pipelines", async () => {
        const pipelines = await listPipelines();
        const slugs = pipelines.map((p) => p.slug);
        expect(slugs).toContain("test-feature");
        expect(slugs).toContain("old-feature");
    });

    it("sorts active pipelines before completed ones", async () => {
        const pipelines = await listPipelines();
        const activeIdx = pipelines.findIndex((p) => p.slug === "test-feature");
        const archivedIdx = pipelines.findIndex((p) => p.slug === "old-feature");
        expect(activeIdx).toBeLessThan(archivedIdx);
    });

    it("computes total cost from token counts", async () => {
        const pipelines = await listPipelines();
        const active = pipelines.find((p) => p.slug === "test-feature")!;
        expect(active.totalCost).toBeGreaterThan(0);
    });
});

// =========================================================================
// B. Flight Data Envelope Parsing
// =========================================================================

describe("B. Flight Data Envelope", () => {
    it("reads envelope-format _FLIGHT_DATA.json and unwraps items array", async () => {
        const telemetry = await getPipelineTelemetry("test-feature");
        expect(telemetry.flightData.length).toBeGreaterThan(0);
        // Verify it's an array of ItemSummary, not the envelope itself
        expect(Array.isArray(telemetry.flightData)).toBe(true);
        expect(telemetry.flightData[0]).toHaveProperty("key");
        expect(telemetry.flightData[0]).toHaveProperty("outcome");
    });

    it("validates envelope version field exists in raw file", async () => {
        const raw = await fs.readFile(
            path.join(FIXTURES_DIR, "in-progress", "test-feature_FLIGHT_DATA.json"),
            "utf-8",
        );
        const envelope: FlightDataEnvelope = JSON.parse(raw);
        expect(envelope.version).toBe(1);
        expect(envelope.featureSlug).toBe("test-feature");
        expect(envelope.generatedAt).toBeDefined();
        expect(Array.isArray(envelope.items)).toBe(true);
    });

    it("also handles archived envelope-format flight data", async () => {
        const telemetry = await getPipelineTelemetry("old-feature");
        expect(telemetry.flightData.length).toBeGreaterThan(0);
        expect(telemetry.flightData[0]).toHaveProperty("key");
    });
});

// =========================================================================
// C. State Contract Validation
// =========================================================================

describe("C. State Contract", () => {
    it("includes errorLog field", async () => {
        const telemetry = await getPipelineTelemetry("test-feature");
        expect(telemetry.state).toHaveProperty("errorLog");
        expect(Array.isArray(telemetry.state.errorLog)).toBe(true);
    });

    it("archived state has populated errorLog entries", async () => {
        const telemetry = await getPipelineTelemetry("old-feature");
        expect(telemetry.state.errorLog.length).toBeGreaterThan(0);
        const entry = telemetry.state.errorLog[0];
        expect(entry).toHaveProperty("timestamp");
        expect(entry).toHaveProperty("itemKey");
        expect(entry).toHaveProperty("message");
    });

    it("state items use only contract-valid statuses: pending|done|failed|na", async () => {
        const telemetry = await getPipelineTelemetry("test-feature");
        const validStatuses = new Set(["pending", "done", "failed", "na"]);
        for (const item of telemetry.state.items) {
            expect(validStatuses.has(item.status)).toBe(true);
        }
    });

    it("state items include all known pipeline step keys", async () => {
        const telemetry = await getPipelineTelemetry("test-feature");
        const keys = telemetry.state.items.map((i) => i.key);
        // Pre-deploy
        expect(keys).toContain("schema-dev");
        expect(keys).toContain("backend-dev");
        expect(keys).toContain("frontend-dev");
        expect(keys).toContain("backend-unit-test");
        expect(keys).toContain("frontend-unit-test");
        expect(keys).toContain("code-cleanup");
        // Deploy
        expect(keys).toContain("push-infra");
        expect(keys).toContain("poll-infra-plan");
        expect(keys).toContain("create-draft-pr");
        expect(keys).toContain("push-app");
        expect(keys).toContain("poll-app-ci");
        // Post-deploy
        expect(keys).toContain("integration-test");
        expect(keys).toContain("live-ui");
        // Finalize
        expect(keys).toContain("docs-archived");
        expect(keys).toContain("create-pr");
    });

    it("workflowType is a recognized value", async () => {
        const telemetry = await getPipelineTelemetry("test-feature");
        const validTypes = new Set(["fullstack", "backend-only", "frontend-only", "infra-only"]);
        expect(validTypes.has(telemetry.state.workflowType)).toBe(true);
    });
});

// =========================================================================
// D. Real-Time Display Correctness
// =========================================================================

describe("D. Real-Time Display", () => {
    it("identifies the in-progress step as the last flight item with outcome 'in-progress'", async () => {
        const telemetry = await getPipelineTelemetry("test-feature");
        const inProgress = telemetry.flightData.filter((f) => f.outcome === "in-progress");
        expect(inProgress.length).toBe(1);
        expect(inProgress[0].key).toBe("code-cleanup");
        expect(inProgress[0].durationMs).toBe(0);
        expect(inProgress[0].startedAt).toBe(inProgress[0].finishedAt);
    });

    it("in-progress item has live-updating token counts (non-zero)", async () => {
        const telemetry = await getPipelineTelemetry("test-feature");
        const active = telemetry.flightData.find((f) => f.outcome === "in-progress")!;
        expect(active.inputTokens).toBeGreaterThan(0);
        expect(active.outputTokens).toBeGreaterThan(0);
        expect(Object.values(active.toolCounts).reduce((a, b) => a + b, 0)).toBeGreaterThan(0);
    });

    it("shows intents for the active step", async () => {
        const telemetry = await getPipelineTelemetry("test-feature");
        const active = telemetry.flightData.find((f) => f.outcome === "in-progress")!;
        expect(active.intents.length).toBeGreaterThan(0);
    });

    it("correctly computes cost with Claude Opus 4 pricing", async () => {
        const telemetry = await getPipelineTelemetry("test-feature");
        let expectedCost = 0;
        for (const item of telemetry.flightData) {
            expectedCost +=
                (item.inputTokens * 15 +
                    item.outputTokens * 75 +
                    item.cacheReadTokens * 1.5 +
                    item.cacheWriteTokens * 3.75) /
                1_000_000;
        }

        const pipelines = await listPipelines();
        const active = pipelines.find((p) => p.slug === "test-feature")!;
        expect(active.totalCost).toBeCloseTo(expectedCost, 6);
    });

    it("computes overall progress: done items / total items (excl na)", async () => {
        const telemetry = await getPipelineTelemetry("test-feature");
        const nonNa = telemetry.state.items.filter((i) => i.status !== "na");
        const done = nonNa.filter((i) => i.status === "done");
        expect(nonNa.length).toBeGreaterThan(done.length); // some pending
        expect(done.length).toBeGreaterThan(0); // some completed
    });
});

// =========================================================================
// E. Multi-File Correlation
// =========================================================================

describe("E. Multi-File Correlation", () => {
    it("cross-references _FLIGHT_DATA items with _STATE items by key", async () => {
        const telemetry = await getPipelineTelemetry("test-feature");
        const stateKeys = new Set(telemetry.state.items.map((i) => i.key));
        for (const flight of telemetry.flightData) {
            expect(stateKeys.has(flight.key)).toBe(true);
        }
    });

    it("handles retry loops: multiple items with same key, different attempts", async () => {
        const telemetry = await getPipelineTelemetry("test-feature");
        const backendTests = telemetry.flightData.filter((f) => f.key === "backend-unit-test");
        expect(backendTests.length).toBe(2);
        expect(backendTests[0].attempt).toBe(1);
        expect(backendTests[0].outcome).toBe("failed");
        expect(backendTests[1].attempt).toBe(2);
        expect(backendTests[1].outcome).toBe("completed");
    });

    it("pending state items may not appear in flight data yet", async () => {
        const telemetry = await getPipelineTelemetry("test-feature");
        const flightKeys = new Set(telemetry.flightData.map((f) => f.key));
        const pendingStateItems = telemetry.state.items.filter((i) => i.status === "pending");
        // At least some pending items should not be in flight data
        const missingFromFlight = pendingStateItems.filter((i) => !flightKeys.has(i.key));
        expect(missingFromFlight.length).toBeGreaterThan(0);
    });

    it("correlations work identically from archive", async () => {
        const telemetry = await getPipelineTelemetry("old-feature");
        const stateKeys = new Set(telemetry.state.items.map((i) => i.key));
        for (const flight of telemetry.flightData) {
            expect(stateKeys.has(flight.key)).toBe(true);
        }
    });

    it("reads spec markdown file", async () => {
        const spec = await getSpecMarkdown("test-feature");
        expect(spec).toContain("Test Feature Spec");
        expect(spec.length).toBeGreaterThan(50);
    });

    it("reads archived spec markdown", async () => {
        const spec = await getSpecMarkdown("old-feature");
        expect(spec).toContain("Old Feature Spec");
    });
});

// =========================================================================
// F. Edge Cases & Archive Behavior
// =========================================================================

describe("F. Edge Cases", () => {
    it("detects circuit breaker errors", async () => {
        const telemetry = await getPipelineTelemetry("old-feature");
        const errorItem = telemetry.flightData.find(
            (f) => f.outcome === "error" && f.errorMessage?.includes("circuit breaker"),
        );
        expect(errorItem).toBeDefined();
        expect(errorItem!.key).toBe("backend-unit-test");
        expect(errorItem!.attempt).toBe(1);
    });

    it("retry succeeded after circuit breaker", async () => {
        const telemetry = await getPipelineTelemetry("old-feature");
        const retries = telemetry.flightData.filter((f) => f.key === "backend-unit-test");
        expect(retries[0].outcome).toBe("error");
        expect(retries[1].outcome).toBe("completed");
        expect(retries[1].attempt).toBe(2);
    });

    it("completed archived pipeline has all items done or na", async () => {
        const telemetry = await getPipelineTelemetry("old-feature");
        for (const item of telemetry.state.items) {
            expect(["done", "na"]).toContain(item.status);
        }
    });

    it("handles na-status items (workflow-specific skips)", async () => {
        const telemetry = await getPipelineTelemetry("old-feature");
        const naItems = telemetry.state.items.filter((i) => i.status === "na");
        expect(naItems.length).toBeGreaterThan(0);
    });

    it("returns file mtime for freshness detection", async () => {
        const mtime = await getFlightDataMtime("test-feature");
        expect(mtime).not.toBeNull();
        // Should be a valid ISO timestamp
        expect(new Date(mtime!).getTime()).toBeGreaterThan(0);
    });

    it("reads markdown telemetry files (summary, terminal-log, trans)", async () => {
        const telemetry = await getPipelineTelemetry("test-feature");
        expect(telemetry.markdownFiles?.summary).toContain("Pipeline Summary");
        expect(telemetry.markdownFiles?.terminalLog).toContain("Terminal Log");
        expect(telemetry.markdownFiles?.transitionLog).toContain("Transition Log");
    });

    it("reads archived markdown files", async () => {
        const telemetry = await getPipelineTelemetry("old-feature");
        expect(telemetry.markdownFiles?.summary).toContain("old-feature");
        expect(telemetry.markdownFiles?.terminalLog).toContain("backend-unit-test");
    });

    it("handles missing slug gracefully", async () => {
        const telemetry = await getPipelineTelemetry("nonexistent-slug");
        expect(telemetry.state).toEqual(expect.objectContaining({ feature: "", items: [] }));
        expect(telemetry.flightData).toEqual([]);
    });

    it("structured error messages parse correctly", async () => {
        const telemetry = await getPipelineTelemetry("test-feature");
        const failedItem = telemetry.flightData.find(
            (f) => f.key === "backend-unit-test" && f.outcome === "failed",
        );
        expect(failedItem?.errorMessage).toBeDefined();
        const parsed = JSON.parse(failedItem!.errorMessage!);
        expect(parsed.fault_domain).toBe("backend");
        expect(parsed.diagnostic_trace).toBeDefined();
    });

    it("headAfterAttempt is present on completed steps", async () => {
        const telemetry = await getPipelineTelemetry("test-feature");
        const completed = telemetry.flightData.filter((f) => f.outcome === "completed" && f.headAfterAttempt);
        expect(completed.length).toBeGreaterThan(0);
    });

    it("screenshots directory exists in archived pipeline", () => {
        const screenshotsDir = path.join(
            FIXTURES_DIR, "archive", "features", "old-feature", "screenshots",
        );
        expect(existsSync(screenshotsDir)).toBe(true);
    });

    it("flight data item order is completion order, not DAG order", async () => {
        const telemetry = await getPipelineTelemetry("test-feature");
        const keys = telemetry.flightData.map((f) => `${f.key}:${f.attempt}`);
        // backend-dev and frontend-dev ran in parallel — frontend finished after backend
        const backendIdx = keys.indexOf("backend-dev:1");
        const frontendIdx = keys.indexOf("frontend-dev:1");
        // Both should exist
        expect(backendIdx).toBeGreaterThanOrEqual(0);
        expect(frontendIdx).toBeGreaterThanOrEqual(0);
    });
});

// =========================================================================
// G. Things That Should NOT Happen
// =========================================================================

describe("G. Safety Guards", () => {
    it("never reads .tmp files (path-traversal slug test)", async () => {
        const telemetry = await getPipelineTelemetry("test.tmp");
        // .tmp is safe because the slug regex allows dots? No — SAFE_SLUG_RE = /^[a-zA-Z0-9_-]+$/
        // "test.tmp" contains a dot, so it should return defaults
        expect(telemetry.state).toEqual(expect.objectContaining({ feature: "" }));
    });

    it("rejects path traversal slugs", async () => {
        const slugs = ["../../etc/passwd", "../secret", "foo/bar"];
        for (const slug of slugs) {
            const telemetry = await getPipelineTelemetry(slug);
            expect(telemetry.state.feature).toBe("");
            expect(telemetry.flightData).toEqual([]);
        }
    });

    it("returns empty for nonexistent directory (pipeline not started)", async () => {
        const original = process.env.TARGET_APP_PATH;
        process.env.TARGET_APP_PATH = "/tmp/nonexistent-dagent-dir";
        try {
            const pipelines = await listPipelines();
            expect(pipelines).toEqual([]);
        } finally {
            process.env.TARGET_APP_PATH = original;
        }
    });
});
